server:
  port: 9999
spring:
  datasource:
    url: jdbc:h2:file:/Users/sudhamohanpanda/data/demo
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2dev
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
